source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls"))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import WorkView, CreateWork, DeleteWork, UpdateWork
from webapp.views.projects import ProjectView, IndexView_project, UpdateProject, DeleteProject, CreateProject

app_name = "webapp"

urlpatterns = [
    path('', IndexView_project.as_view(), name="index"),
    path('project/<int:pk>/', ProjectView.as_view(), name="project_view"),
    path('project/<int:pk>/update/', UpdateProject.as_view(), name="update_project"),
    path('project/<int:pk>/delete/', DeleteProject.as_view(), name="delete_project"),
    path('project/add/', CreateProject.as_view(), name="create_project"),
    path('project/<int:pk>/work/add/', CreateWork.as_view(), name="project_work_create"),
    path('work/<int:pk>/', WorkView.as_view(), name="work_view"),
    path('work/<int:pk>/update/', UpdateWork.as_view(), name="update_work"),
    path('work/<int:pk>/delete/', DeleteWork.as_view(), name="delete_work"),

]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    class Meta:
        abstract = True


class Status(BaseModel):
    status = models.CharField(max_length=100, null=True, blank=True, verbose_name="Статус")

    def __str__(self):
        return f"{self.status}"

    class Meta:
        db_table = "statuses"
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"


class Type(BaseModel):
    type = models.CharField(max_length=100, null=True, blank=True, verbose_name="Тип")

    def __str__(self):
        return f"{self.type}"

    class Meta:
        db_table = "types"
        verbose_name = "Тип"
        verbose_name_plural = "Типы"


class Work(BaseModel):
    summary = models.CharField(max_length=100, null=False, blank=False, verbose_name="Заголовок")
    description = models.TextField(max_length=100, null=True, blank=True, verbose_name="Описание")
    status = models.ForeignKey("webapp.Status", on_delete=models.CASCADE, related_name="Statuses",
                               verbose_name="Статус")
    types = models.ManyToManyField("webapp.Type", related_name="works", blank=True)
    project = models.ForeignKey("webapp.Project", null=True, blank=True, on_delete=models.CASCADE, related_name="tasks",
                                verbose_name="Проект")

    def __str__(self):
        return f"{self.pk}. {self.description} - {self.status} - {self.summary} - {self.types}"

    class Meta:
        db_table = "works"
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"


class Project(models.Model):
    users = models.ManyToManyField(get_user_model(), related_name="projects", verbose_name="Пользователь")
    name = models.CharField(max_length=30, verbose_name="Название")
    description_project = models.TextField(max_length=150, blank=True, verbose_name="Описание")
    start_date = models.DateField(verbose_name="Дата начала")
    finish_date = models.DateField(verbose_name="Дата окончания")

    def __str__(self):
        return f"{self.pk}. {self.user} {self.start_date} - {self.name} - {self.description_project}"

    def get_absolute_url(self):
        return reverse("webapp:project_view", kwargs={"pk": self.pk})

    def upper(self):
        return self.name.upper()

    class Meta:
        db_table = "projects"
        verbose_name = "Проект"
        verbose_name_plural = "Проекты"
        permissions = [('add_users_in_project', 'Добавление пользователей в проект')]

# Create your models here.

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets, DateInput

from webapp.models import Work, Project


class WorkForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = ["summary", "description", "status", "types"]
        widgets = {
            "types": widgets.CheckboxSelectMultiple
        }

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if len(description) > 100:
            raise ValidationError("Длина описания должна быть меньше 100 символов")
        return description

    def clean_summary(self):
        summary = self.cleaned_data.get('summary')
        if len(summary) > 100:
            raise ValidationError("Длина заголовка должна быть меньше 100 символов")
        return summary


class UserWorkForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = ["summary", "description", "status", "types"]


class UserProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description_project", "finish_date"]


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description_project", "start_date", "finish_date"]
        widgets = {
            "start_date": DateInput(attrs={'type': 'date'}),
            "finish_date": DateInput(attrs={'type': 'date'})
        }

    def clean_description_project(self):
        description_project = self.cleaned_data.get('description_project')
        if len(description_project) > 150:
            raise ValidationError("Длина описания должна быть меньше 100 символов")
        return description_project

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) > 100:
            raise ValidationError("Длина наименования должна быть меньше 50 символов")
        return name

class WorkDeleteForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = ["summary"]

    def clean_title(self):
        summary = self.cleaned_data.get("summary")
        if self.instance.summary != summary:
            raise ValidationError("Названия не совпадают")
        return summary

class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти')

source/webapp/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from django.shortcuts import render
from django.utils.http import urlencode

from django.views import View
from django.views.generic import TemplateView, ListView

from webapp.forms import WorkForm, SearchForm
from webapp.models import Work



class IndexView(ListView):
    model = Work
    template_name = "index.html"
    context_object_name = "workes"
    ordering = "-updated_at"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return Work.objects.filter(Q(summary__icontains=self.search_value))
        return Work.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({'search': self.search_value})
            context['query'] = query
            context['search'] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")


class WorkView(TemplateView):
    template_name = "work_view.html"

    def get_context_data(self, **kwargs):
        pk = kwargs.get("pk")
        work = get_object_or_404(Work, pk=pk)
        kwargs["work"] = work
        return super().get_context_data(**kwargs)


class UpdateWork(View):

    def dispatch(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        self.work = get_object_or_404(Work, pk=pk)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if request.method == "GET":
            form = WorkForm(initial={
                "summary": self.work.summary,
                "description": self.work.description,
                "status": self.work.status,
                "types": self.work.types.all
            })
            return render(request, "update.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = WorkForm(data=request.POST)
        if form.is_valid():
            types = form.cleaned_data.pop('types')
            self.work.summary = form.cleaned_data.get("summary")
            self.work.description = form.cleaned_data.get("description")
            self.work.status = form.cleaned_data.get("status")
            self.work.types.all = form.cleaned_data.get("types")
            self.work.save()
            self.work.types.set(types)
            return redirect("work_view", pk=self.work.pk)
        return render(request, "update.html", {"form": form})


class CreateWork(View):
    def get(self, request, *args, **kwargs):
        if request.method == "GET":
            form = WorkForm()
            return render(request, "create.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = WorkForm(data=request.POST)
        if form.is_valid():
            summary = form.cleaned_data.get("summary")
            description = form.cleaned_data.get("description")
            status = form.cleaned_data.get("status")
            types = form.cleaned_data.get("types")
            new_work = Work.objects.create(summary=summary, description=description, status=status)
            new_work.types.set(types)
            return redirect("work_view", pk=new_work.pk)
        return render(request, "create.html", {"form": form})


class DeleteWork(View):

    def dispatch(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        self.work = get_object_or_404(Work, pk=pk)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if request.method == "GET":
            return render(request, "delete.html", {"work": self.work})

    def post(self, request, *args, **kwargs):
        self.work.delete()
        return redirect("index")

source/webapp/views/base_view.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views import View


class UpdateView(View):
   form_class = None
   template_name = None
   redirect_url = ''
   model = None
   key_kwarg = 'pk'
   context_key = 'object'

   def get(self, request, *args, **kwargs):
       self.object = self.get_object()
       form = self.form_class(instance=self.object)
       context = self.get_context_data(form=form)
       return render(request, self.template_name, context=context)



   def post(self, request, *args, **kwargs):
       self.object = self.get_object()
       form = self.form_class(instance=self.object, data=request.POST)
       if form.is_valid():
           return self.form_valid(form)
       else:
           return self.form_invalid(form)


   def form_valid(self, form):
       self.object = form.save()
       return redirect(self.get_redirect_url())

   def form_invalid(self, form):
       context = self.get_context_data(form=form)
       return render(self.request, self.template_name, context=context)

   def get_object(self):
       pk = self.kwargs.get(self.key_kwarg)
       return get_object_or_404(self.model, pk=pk)

   def get_context_data(self, **kwargs):
       context = self.kwargs.copy()
       context[self.context_key] = self.object
       context.update(kwargs)
       return context

   def get_redirect_url(self):
       return self.redirect_url

source/webapp/views/projects.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.http import request
from django.shortcuts import redirect, get_object_or_404

from django.urls import reverse
from django.utils.http import urlencode

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import SearchForm, ProjectForm, UserProjectForm
from webapp.models import Project


class IndexView_project(ListView):
    model = Project
    template_name = "projects/project_list.html"
    context_object_name = "projects"
    ordering = "name"
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return Project.objects.filter(Q(name__icontains=self.search_value))
        return Project.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({'search': self.search_value})
            context['query'] = query
            context['search'] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")


class ProjectView(DetailView):
    template_name = "projects/project_view.html"
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = self.object.tasks
        return context


class UpdateProject(PermissionRequiredMixin, UpdateView):
    form_class = ProjectForm
    template_name = "projects/project_update.html"
    model = Project


    def get_form_class(self):
        if self.request.GET.get("is_admin"):
            return ProjectForm
        return UserProjectForm

    def get_success_url(self):
        return reverse("webapp:project_view", kwargs={"pk": self.object.pk})


class DeleteProject(DeleteView):
    model = Project

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:index")


class CreateProject(LoginRequiredMixin , CreateView):
    form_class = ProjectForm
    template_name = "projects/project_create.html"


    def get_success_url(self):
        return reverse("webapp:project_view", kwargs={"pk": self.object.pk})

source/webapp/views/works.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import request
from django.shortcuts import get_object_or_404, redirect

from django.urls import reverse, reverse_lazy

from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import WorkForm, UserWorkForm, WorkDeleteForm
from webapp.models import Work, Project


class WorkView(DetailView):
    template_name = "works/work_view.html"
    model = Work

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.object.project
        return context


class UpdateWork(UpdateView):
    form_class = WorkForm
    template_name = "works/update.html"
    model = Work
    permission_required = 'webapp.update_project'

    def has_permission(self):
        return super().has_permission() or self.get_object().user == self.request.user

    def get_form_class(self):
        if self.request.GET.get("is_admin"):
            return WorkForm
        return UserWorkForm

    def get_success_url(self):
        return reverse("webapp:work_view", kwargs={"pk": self.object.pk})


class DeleteWork(DeleteView):
    model = Work
    template_name = "works/delete.html"
    success_url = reverse_lazy('webapp:index')
    form_class = WorkDeleteForm
    permission_required = 'webapp.delete_project'

    def has_permission(self):
        return super().has_permission() or self.get_object().user == self.request.user

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:project_view", kwargs={"pk": self.object.project.pk})


class CreateWork(LoginRequiredMixin, CreateView):
    form_class = WorkForm
    template_name = "works/create.html"


    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get("pk"))
        form.instance.project = project
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:work_view", kwargs={"pk": self.object.pk})

source/webapp/templates/projects/project_create.html
{% extends "base.html" %}
{% block title %}Создание нового проекта{% endblock %}

{% block content %}
    <h1>Create Project</h1>
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Создать" %}
    </form>
    <a href="{% url "webapp:index" %}">На главную</a>
{% endblock %}

source/webapp/templates/projects/project_delete.html
{% extends "base.html" %}
{% block title %}Удаление задачи{% endblock %}

{% block content %}
    <h2>Введите название проекта ({{ project.name }}) для удаления</h2>
<form action="" method="post">
{% csrf_token %}
    {% include "partial/form.html" with button_text="Удалить" %}
</form>
    <a href="{% url "webapp:project_view" work.pk %}">Нет</a>
{% endblock %}

source/webapp/templates/projects/project_list.html
{% extends "base.html" %}
{% load static %}
{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_project" %}">Создание проекта</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    {% include "partial/search.html" %}
    <h1>Проекты</h1>
    <div class="row">
        {% for project in projects %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.name }}</h5>
                        <a href="{% url "webapp:project_view" project.pk %}" class="card-link">О проекте</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if is_paginated %}
            {% include "partial/pagination.html" %}
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/projects/project_update.html
{% extends "base.html" %}
{% block title %}Редактирование проекта{% endblock %}

{% block content %}
    <h1>Update Project</h1>
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Изменить"%}
    </form>
    <a href="{% url "webapp:index" %}">На главную</a>
{% endblock %}

source/webapp/templates/projects/project_view.html
{% extends "base.html" %}
{% block nav %}
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:project_work_create" project.pk %}">Добавление задачи в проект</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "webapp:update_project" project.pk %}">Редактировать проект</a>
    </li>
    <li class="nav-item">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#projectDeleteModal">
            Удалить
        </button>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
    {{ test }}
    <p>Пользователи:</p>
    {% for user in project.users.all %}
        <p>{{ user }}</p>
        </p>
    {% endfor %}

    <p>
        Название проекта: {{ project.name }}
    </p>
    <p>
      Описание:  {{ project.description_project }}
    </p>
    <p>
       Дата начала: {{ project.start_date }}
    </p>
    <p>
       Дата сдачи: {{ project.finish_date }}
    </p>
    <p>Задачи проекта:</p>
    {% for task in project.tasks.all %}
        <p>{{ task.summary }}</p>
        {% if request.user.is_authenticated %}
        <a href="{% url "webapp:update_work" task.pk %}">Изменить</a>
        <a href="{% url "webapp:delete_work" task.pk %}">Удалить</a>
        {% endif %}
        </p>
    {% empty %}
        <p>Нет задач в проекте</p>
    {% endfor %}

    <a href="{% url "webapp:index" %}">На главную</a>


    <div class="modal fade" id="projectDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="projectDeleteModal">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Вы уверены что хотите удалить проект {{ project.name }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{% url "webapp:delete_project" project.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Да</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}